export const ActionTypes = {
    STORE_USER_TOKEN_EMAIL: 'STORE_USER_TOKEN_EMAIL',
    STORE_CURRENT_USER: 'STORE_CURRENT_USER',
    STORE_USER_UPDATED: 'STORE_USER_UPDATED',
    STORE_PAYMENT_RESPONSE: 'STORE_PAYMENT_RESPONSE',
    STORE_USER_TRANSACTIONS: 'STORE_USER_TRANSACTIONS',
    STORE_RECIPIENT_DETAILS: "STORE_RECIPIENT_DETAILS",
    STORE_TRANSFER_ACCESS: "STORE_TRANSFER_ACCESS",
    STORE_BANK_LIST: "STORE_BANK_LIST",
    STORE_USERS_LIST: "STORE_USERS_LIST",
    LOG_OUT: "LOG_OUT",
}